### ISSUE TITLE
Discussion: Should we use Rollup?

### ISSUE THREAD

**Issue by whymarrh** [MetaMask/metamask-module-template#11]
Previously, we tried using `tslib`.

This seems to be _a thing_, and there are options:

- https://twitter.com/mjackson/status/1265674238544904197
- https://twitter.com/mjackson/status/1257381774352691203
- https://twitter.com/jaffathecake/status/1145979217852678144

**Comment by rekmarks** [comment]
If we do use Rollup and ship different versions, we need to consider whether they are bundles or something else.

From @kumavis:
> it seems like the package exports (cjs, esm) are all bundles. While we can include a bundle in our export, we should not make it the default.

**Comment by mcmire** [comment]
Noticed this issue. What would the benefit of using Rollup be?

**Comment by mcmire** [comment]
I'm going to close this issue as there doesn't seem to be a need for this, but happy to re-open if we want this.
