### ISSUE TITLE
Add automated docs generation and versioning

### ISSUE THREAD

**Issue by Mrtenz** [MetaMask/metamask-module-template#119]
In the utils repository among others we have [a workflow for publishing automatically generated docs](https://github.com/MetaMask/utils/blob/main/.github/workflows/publish-docs.yml), generated by `typedoc`. Right now it pushes the docs whenever a commit is pushed to `main`. We should adapt this workflow to do some versioning (i.e., only publish on releases, to a versioned folder), similar to how it's done in the [`phishing-warning` repo](https://github.com/MetaMask/phishing-warning/tree/main/.github/workflows), and add this workflow to the module template.

**Comment by Gudahtt** [comment]
Closed by #123
