### ISSUE TITLE
Consider enabling Dependabot updates for MetaMask packages

### ISSUE THREAD

**Issue by whymarrh** [MetaMask/metamask-module-template#14]
It might be possible to enable Dependabot updates for `@metamask/*`

See: [_Configuration options for dependency updates_](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#allow)

Note: this is separate from security updates, this would be a higher update frequency

**Comment by rekmarks** [comment]
We have all kinds of plans related to this, and they probably don't involve Dependabot.
