### ISSUE TITLE
this should be a yeoman template repo (?)

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-module-template#25]
maybe!
granular templates that can take arguments
should easy pulling in configurations to our existing repos

**Comment by danfinlay** [comment]
Other templates to add:
- [ ] React component
- [ ] Web Dapp
- [ ] Snap

**Comment by kumavis** [comment]
worth noting that github repo templates include github settings and yeoman generators likely couldnt catch that

**Comment by kumavis** [comment]
started a thing https://github.com/MetaMask/metamask-yeoman-generators

**Comment by rekmarks** [comment]
Maybe we should have a Yeoman template thingamabob, but this ain't it.
