### ISSUE TITLE
RFC: Remove lockfile

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-module-template#27]
The argument is that lockfiles are mostly good for preserving the security for an end distribution of an application. Locking the dependencies of intermediate modules can inadvertently prevent the deduplication of dependencies in a final app bundle.

By removing the lockfile, we allow semver to operate properly "through" the resulting module, allowing consumers to receive dependency updates without rebuilds & updates of each intermediate module.

**Comment by Gudahtt** [comment]
We should be using a lockfile for all projects, including libraries. It seems like you've misunderstood what lockfiles do.

>The argument is that lockfiles are mostly good for preserving the security for an end distribution of an application.

They ensure a consistent development environment between CI and all contributors. We can't hope to debug the same issues together if we're each using different versions of each dependency.

>Locking the dependencies of intermediate modules can inadvertently prevent the deduplication of dependencies in a final app bundle.

This is not how lockfiles work. The lockfile for a library is ignored by anyone consuming that library.

This is what shrinkwrap files, pinned dependencies, and bundled dependencies do. I agree that we should avoid those three things. But this is not what a lockfile does.
