### ISSUE TITLE
Decide where tests should live

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-module-template#32]
This repository has tests in a top-level `test` directory, but lately we've been migrating tests to be alongside the code under test (as is done in the controllers repo, the extension, and mobile).

Ideally we'd use the same pattern everywhere of having tests alongside the code under test. If we're not going to do that, we should have some guidance on where we'll follow each pattern, and why.

**Comment by rekmarks** [comment]
Tests are going to be colocated everywhere. I'll PR this.
